<?php 
define('DB_TYPE','mysql'); 
define('DB_HOST','localhost'); 
define('DB_NAME','cms'); 
define('DB_USER','root'); 
define('DB_PWD',''); 
define('DB_PORT','3306'); 
define('DB_PREFIX','thinkphp'); 
?>